# ingress.service.yaml

---
apiVersion: v1
kind: Service
metadata:
  name: green-service
spec:
  type: NodePort
  selector:
    app: green-nginx   # 綁定標記為 green-nginx 的 Pod
  ports:
    - protocol: TCP
      port: 80

---
apiVersion: v1
kind: Service
metadata:
  name: red-service
spec:
  type: NodePort
  selector:
    app: red-nginx   # 綁定標記為 red-nginx 的 Pod
  ports:
    - protocol: TCP
      port: 80
