# secret.deployment.yaml

---
apiVersion: apps/v1        # 使用 v1 版本的 api
kind: Deployment      # 類型為 Deployment
metadata:
  name: webserver         # Deployment 的名稱
spec:                 # 其他規格描述(Deployment)
  replicas: 3         # 運行三個 Pod (replicas: 3)
  selector:
    matchLabels:
      app: webserver
  template:           # 描述每個 Pod 規格
    metadata:
      labels: 
        app: webserver    # 標記名稱
    spec:             # 其他規格描述(Pod)
      containers:     # 描述容器內容
      - name: my-pod   # 將容器名稱
        image: andy6804tw/docker-nodejs-tutorial  # 使用 nginx 映像檔
        ports:
        - containerPort: 8080 # 指定使用 8080 port
        volumeMounts:
        - mountPath: /tmp/conf # 將綁定 mysecret 的 Volume 掛載到 /tmp/conf 目錄下
          name: secret-volume
        env:                    # 將綁定的 mysecret 以環境變數的方式掛載
        - name: NODE_ENV    
          valueFrom:
            secretKeyRef:
              name: mysecret   
              key: NODE_ENV     # 指定綁定哪個 key
      volumes:
      - name: secret-volume   
        secret:
          secretName: mysecret   # 指定使用名為 mysecret 的 Secret 物件

